name: mosdef-workshop
channels:
  - conda-forge
  - bioconda
dependencies:
  - mbuild
  - foyer
  - nglview
  - hoomd
  - mosdef_cassandra
  - gromacs
  - py3dmol
  - matplotlib
  - panedr
  - mdtraj
  - forcefield-utilities
  - pip
  - pip:
      - git+https://github.com/mosdef-hub/gmso.git@develop
